### ISSUE TITLE
error: unsupported linker arg: `--no-undefined-version`

### ISSUE THREAD

**Issue by goniz** [uber/hermetic_cc_toolchain#103]
Hi

We're using 'rules_rust' with 'uber/hermetic_cc_toolchain' and its working great!
Recently we have tried to update to Rustc 1.70.0 (using latest rules_rust v0.25) and we get:
```
error: unsupported linker arg: --no-undefined-version
```

From what I've managed to figure out, upstream LLVM started using this flag by default (on builds with exported symbols) and this is propagating through rustc to the Zig linker.

(Seems to be fixed in https://github.com/rust-cross/cargo-zigbuild/pull/110 as well)

Is it possible to add support for it?

Thanks!

**Comment by goniz** [comment]
Seems to be fixed in https://github.com/rust-cross/cargo-zigbuild/pull/110 as well

**Comment by goniz** [comment]
@motiejus is this issue actually relevant to this repo? should I open the issue in Zig's repo?

**Comment by motiejus** [comment]
> @motiejus is this issue actually relevant to this repo? should I open the issue in Zig's repo?

Yes. Hermetic_cc_toolchain does not interpret commandine arguments, everything gets passed to the underlying `zig cc`.
