### ISSUE TITLE
separate examples and downloadable repository

### ISSUE THREAD

**Issue by motiejus** [uber/hermetic_cc_toolchain#15]
Currently all the things below are intermixed in a flat-ish hierarchy of bazel-zig-cc:
- files that are designed to be loaded by third parties: `WORKSPACE` and `toolchain/`.
- repository bookkeeping (gazelle, lint, release scripts)
- `tests/`.

The original idea was to have the "minimal required things" be in the top level of the repository; meaning the `WORKSPACE` file would have only such contents: `workspace(name = "bazel-zig-cc")`; everything else should be hidden in sub-directories. However, I can't figure out a way to make bookeeping work -- which depends on Gazelle, Go and all that fun stuff. Basically, it's a conflict of what should be in the `WORKSPACE`.

Concretely:
1. Could the "book-keeping" `WORKSPACE` be in it's sub-folder, and the bookkeeping commands be run from there? To be clear, we want the bookkeeping commands to access the full repository.
2. Can this be made easier with bzlMod? Looking for bzlMod experts here.

**Comment by motiejus** [comment]
> If I understand correctly, when you import a repository, you don't actually load it's WORKSPACE file

It does:

```
bazel-zig-cc$ mkdir x; cp -r toolchain x/
go-code somewhere$ $ bazel build --override_repository=bazel-zig-cc=/code/bazel-zig-cc/x :usergroups
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 284eb0bb-645a-4c0a-8db6-a085e798a5dd
ERROR: Error computing the main repository mapping: no such package '@bazel-zig-cc//toolchain': No WORKSPACE file found in /home/motiejus/.cache/bazel/_bazel_motiejus/80f026c00534678eecd7f80fa20fddc4/external/bazel-zig-cc
```

If I add a minimal (with the one-line file contents as quoted) or empty `x/WORKSPACE`, it will then Just Work.

So at least it needs a file present.

**Comment by linzhp** [comment]
Yes, it needs the `WORKSPACE` file present, but it doesn't *load* the repos declared in it. So it's fine to make bazel-zig-cc's workspace the bookkeeping workspace, like @laurynasl-uber said.

An experiment you can do is
1. Create a simple repo that doesn't need rules_go, for example, only contains C code
2. Load bazel-zig-cc to compile the C code
3. Verify that neither rules_go or go_sdk is loaded (`bazel query "//external:go_sdk"`)
