### ISSUE TITLE
bzlmod: hermetic_cc_toolchain>2.2.0 registers toolchains by default

### ISSUE THREAD

**Issue by TvdW** [uber/hermetic_cc_toolchain#181]
As of 8a1ca917888f32c4c3106a275d3611d2b3f1bbf6 / #135, the root [MODULE.bazel](https://github.com/uber/hermetic_cc_toolchain/blob/main/MODULE.bazel#L35-L52) contains a call to `register_toolchains` that causes every zig-cc toolchain to be registered if the module is loaded. This means that when loading hermetic_cc_toolchain using bzlmod, it's not possible to only build a single target using this toolchain, as they will be registered by default and picked up by bazel for all compilation.

I believe this to be a bug, as the [README](https://github.com/uber/hermetic_cc_toolchain?tab=readme-ov-file#use-case-always-compile-with-zig-cc) specifically lists this as an _option_.

This could well be a Bazel bug in visibility: I don't think that just _loading_ a module should ever create side-effects like this. Sadly, it still makes it problematic to load hermetic_cc_toolchain via bzlmod.

**Comment by motiejus** [comment]
Certainly not int

**Comment by motiejus** [comment]
Nde

**Comment by zaucy** [comment]
adding `dev_dependency=True` to the `register_toolchains` should prevent the toolchains from being registered by consumers of this module.

**Comment by xuzhenglun** [comment]
it seam like `--incompatible_enable_cc_toolchain_resolution` default to be true in bazel 7.0. I set this flag to false, and host default toolchains works again.
