### ISSUE TITLE
Install instructions still point to /git.sr.ht

### ISSUE THREAD

**Issue by sasha-wing** [uber/hermetic_cc_toolchain#24]
the instructions still point to https://git.sr.ht/~motiejus/bazel-zig-cc/archive/

is it possible to point them to this github repo instead?

**Comment by motiejus** [comment]
Hold on tight. The new release will be v2 and be hosted here, with links to github assets.


There is a lot of work that needs to happen before we are happy with the release (release procedure, CI, some backwards incompatible changes which we also want to test before releasing), and not all of it is on the surface. Bear with us.

Until that happens, please use v1.0.1, exactly as in the README.

**Comment by Gentatsu** [comment]
Thanks mate. That works for me.
