### ISSUE TITLE
repo rename broke builds depending on v1.0.1 release

### ISSUE THREAD

**Issue by pjjw** [uber/hermetic_cc_toolchain#38]
hi, we'd moved over to pulling from sourcehut to here shortly after the move was announced. repo fetch looked like this:

```bazel
http_archive(
    name = "bazel-zig-cc",
    sha256 = "a1c27343c0c5f4a9a5c5ac573f4e5388481380f3f5b09c2a551645808ab2c365",
    strip_prefix = "bazel-zig-cc-1.0.1",
    urls = ["https://github.com/uber/bazel-zig-cc/archive/refs/tags/{}.tar.gz".format(BAZEL_ZIG_CC_VERSION)],
)
```
as all that was in the release was the tag.

this url now serves a 301 redirect to `https://github.com/uber/hermetic_cc_toolchain/archive/refs/tags/v1.0.1.tar.gz` which has a different SHA

**Comment by pjjw** [comment]
i am betting this is not a fixable thing, but just letting you know regardless.

**Comment by motiejus** [comment]
Can you confirm the current urls in the README fix it?

**Comment by pjjw** [comment]
yeah the new stuff works but now we can't build/query/diff against any old revisions without hacking around in the old WORKSPACE file first.

**Comment by motiejus** [comment]
> yeah the new stuff works but now we can't build/query/diff against any old revisions without hacking around in the old WORKSPACE file first.

Perhaps `--override_repository` would work for such cases?

**Comment by sasha-wing-security-ltd** [comment]
I fixed it in my WORKSPACE file with 

```
BAZEL_ZIG_CC_VERSION = "1.0.1"

# https://github.com/uber/bazel-zig-cc
http_archive(
    name = "bazel-zig-cc",
    sha256 = "a1c27343c0c5f4a9a5c5ac573f4e5388481380f3f5b09c2a551645808ab2c365",
    strip_prefix = "bazel-zig-cc-{}".format(BAZEL_ZIG_CC_VERSION),
    urls = ["https://github.com/uber/hermetic_cc_toolchain/archive/refs/tags/v{}.tar.gz".format(BAZEL_ZIG_CC_VERSION)],
)

load("@bazel-zig-cc//toolchain:defs.bzl", zig_toolchains = "toolchains")
```
