### ISSUE TITLE
http_archive repository rename breaking builds on v1.0.1

### ISSUE THREAD

**Issue by FabianHahn** [uber/hermetic_cc_toolchain#39]
(this is related to #38 because it is also result of the repo rename, but I believe is a different issue)

The repository rename in #36 also changed README.md to recommend the following WORKSPACE repository rule:
```
http_archive(
    name = "hermetic_cc_toolchain",
[...]
)
```
However, the existing build rules in the v1.0.1 archives still include each other as `@bazel-zig-cc`. This means that a WORKSPACE definition like the one above will fail with errors such as:
```
INFO: Invocation ID: 28e96ffa-cf39-4c7a-a059-d0f36b5653b1
ERROR: Failed to load Starlark extension '@bazel-zig-cc//toolchain/private:defs.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @bazel-zig-cc
This could either mean you have to add the '@bazel-zig-cc' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.072s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

A simple temporary workaround is to just rename the repository back to `bazel-zig-cc` and everything will work fine. But in the interest of completing the rename (and making the README provide working instructions), could I request a v1.0.2 to be released with the updated build rules that reference the new repository name?

**Comment by motiejus** [comment]
Can you test #40?
 
> <...> could I request a v1.0.2 to be released with the updated build rules that reference the new repository name?

As #40 says, we will be releasing v2 soon enough. I will fix up the instructions and README to use v1.0.1 until that happens.
