### ISSUE TITLE
@zig_sdk//:tools/zig-launcher Does not exist?

### ISSUE THREAD

**Issue by dymart** [uber/hermetic_cc_toolchain#91]
Really great work on the project!! 

Was just going through the most recent release notes (https://github.com/uber/hermetic_cc_toolchain/releases/tag/v2.0.0) while updating and noticed that @zig_sdk//:tools/zig-launcher does not seem to exist.
Seems like it should be @zig_sdk//:tools/zig-wrapper ? 

If I'm mistaken feel free to close the issue.

Thank you,
Dylan

**Comment by motiejus** [comment]
Good catch, thanks! Updated the release notes.
